name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**.rs"

  pull_request:
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always
  REPO_NAME: ${{ github.event.repository.name }}
  COVERAGE_PATH: ./coverage
  CARGO_INSTALL_PATH: ./bin

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust ${{ inputs.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.CARGO_INSTALL_PATH }}

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Install sqlx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: >-
            sqlx-cli
            --no-default-features
            --features rustls,postgres
            --root ${{ env.CARGO_INSTALL_PATH }}

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          ./scripts/init_db.sh --skip-docker

      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust ${{ inputs.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.CARGO_INSTALL_PATH }}

      - name: Install sqlx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: >-
            sqlx-cli
            --no-default-features
            --features rustls,postgres
            --root ${{ env.CARGO_INSTALL_PATH }}

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          ./scripts/init_db.sh --skip-docker

      - name: Test
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: >-
            --skip-clean
            --out Html
            --out Xml
            --output-dir ${{ env.COVERAGE_PATH }}

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ env.REPO_NAME }}
          path: ${{ env.COVERAGE_PATH }}/**/*

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ env.COVERAGE_PATH }}
