name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**.rs"

  pull_request:
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always
  REPO_NAME: ${{ github.event.repository.name }}
  COVERAGE_PATH: ./coverage

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust ${{ inputs.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust ${{ inputs.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: >-
            --skip-clean
            --out Html
            --out Xml
            --output-dir ${{ env.COVERAGE_PATH }}

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ env.REPO_NAME }}
          path: ${{ env.COVERAGE_PATH }}/**/*

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ env.COVERAGE_PATH }}
